version: '3'
services:
  nginx: 
    image: nginx:latest
    networks:
      - app-net
    container_name: production_nginx
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8010
      - 443:4433

  myflaskapp:
    image: flaskapp:latest
    networks:
      - app-net
    container_name: myflaskappcontainer
    expose:
      - "8000"
networks:
  app-net: